### ISSUE TITLE
1.20.4 Cannot place cart with smelter on a dedicated server

### ISSUE THREAD

**Issue by coehlrich** [CreeperHost/StevesCarts2#38]
Attempting to place a cart with a smelter module on a dedicated server fails with this exception in the log output:
```
java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/stevescarts@1.2.5/vswe.stevescarts.modules.addons.ModuleSmelter.getSlot(ModuleSmelter.java:162)
        at TRANSFORMER/stevescarts@1.2.5/vswe.stevescarts.api.modules.ModuleBase.generateSlots(ModuleBase.java:307)
        at TRANSFORMER/stevescarts@1.2.5/vswe.stevescarts.entities.EntityMinecartModular.initModules(EntityMinecartModular.java:421)
        at TRANSFORMER/stevescarts@1.2.5/vswe.stevescarts.entities.EntityMinecartModular.loadModules(EntityMinecartModular.java:314)
        at TRANSFORMER/stevescarts@1.2.5/vswe.stevescarts.entities.EntityMinecartModular.loadModules(EntityMinecartModular.java:289)
        at TRANSFORMER/stevescarts@1.2.5/vswe.stevescarts.entities.EntityMinecartModular.<init>(EntityMinecartModular.java:187)
        at TRANSFORMER/stevescarts@1.2.5/vswe.stevescarts.items.ItemCarts.useOn(ItemCarts.java:63)
        at TRANSFORMER/neoforge@20.4.237/net.neoforged.neoforge.common.CommonHooks.onPlaceItemIntoWorld(CommonHooks.java:515)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.world.item.ItemStack.useOn(ItemStack.java:290)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:363)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1131)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:34)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:8)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:24)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:810)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:162)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:793)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:787)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:109)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:773)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:704)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
Seemingly due to https://github.com/CreeperHost/StevesCarts2/blob/1.20.4/src/main/java/vswe/stevescarts/containers/slots/SlotFurnaceInput.java#L21

**Comment by gigabit101** [comment]
Fixed in 1.2.6
